[tool.isort]
profile = "black"
py_version = 311
force_sort_within_sections = true
skip = ".git,.pytype,.venv"

[tool.pytest.ini_options]
minversion = "7.0"
addopts = [
    "-v",
    "-ra",
    "--strict-markers",
    "--strict-config",
    "-W ignore::DeprecationWarning",
]
xfail_strict = 1
testpaths = [
    "tests",
]

[tool.black]
line-length = 100
target-version = ['py311']
exclude = '(\.eggs|\.git|\.mypy_cache|\.nox|\.tox|.*venv|dist|\.vscode|\.pytype)'